INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Milos', 'Milosevic', '100');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Marko', 'Markovic', '101');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Milan ', 'Milanovic', '102');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Filip', 'Filipovic', '103');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Petar', 'Petrovic', '104');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Mirko ', 'Mirkovic', '105');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Marija', 'Cirkovic', '201');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Jelena', 'Andjelkovic', '202');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Ana', 'Petrovic', '203');
INSERT INTO `radnik` (`ime`, `prezime`, `identifikacioni_broj`) VALUES ('Jovana', 'Radic', '204');
INSERT INTO `komitent` (`pib`, `naziv`, `adresa`, `telefon`, `fax`, `website`, `email`, `registarski_broj`, `sifra_delatnosti`) VALUES ('100000001', 'ABC', 'Beogradska bb', '011789456123', '11789456123', 'abc.com', 'abc@abc.com', '1', '1');
INSERT INTO `komitent` (`pib`, `naziv`, `adresa`, `telefon`, `fax`, `website`, `email`, `registarski_broj`, `sifra_delatnosti`) VALUES ('100000002', 'XYZ', 'Pazarska 1', '011123456789', '011123456789', 'xyz.com', 'xyz@xyz.com', '2', '1');
INSERT INTO `komitent` (`pib`, `naziv`, `adresa`, `telefon`, `fax`, `website`, `email`, `registarski_broj`, `sifra_delatnosti`) VALUES ('100000003', 'Proleteri', 'Proleterska 21', '021147258369', '021147258369', 'prolet.com', 'info@proleter.com', '3', '2');
INSERT INTO `komitent` (`pib`, `naziv`, `adresa`, `telefon`, `fax`, `website`, `email`, `registarski_broj`, `sifra_delatnosti`) VALUES ('100000004', 'Dexyco', 'Zmaj Jovina 33', '021456789', '021456789', 'dexyco.com', 'dexy@dexyco.com', '4', '3');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('1', 'Bela griva', '100', '100', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('2', '1000 zasto, 1000 zato', '2500', '5', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('3', 'Stakleno zvono', '650', '10', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('4', 'Julijin odgovor', '550', '50', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('5', 'Srz zla', '500', '10', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('6', 'Par iz susedstva', '450', '2', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('7', 'Mitovi i legende', '900', '5', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('8', 'Alef', '750', '12', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('9', 'Ponocno sunce', '855', '5', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('10', 'Nordijska mitologija', '960', '3', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('11', 'E bas vam hvala', '890', '5', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('12', 'Covek po imenu Uve', '740', '6', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('13', 'Sestra iz senke', '650', '10', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `artikal` (`kataloski_broj`, `naziv`, `cena`, `stanje_na_lageru`, `naruceno`, `rezervisano`, `otpremljeno`, `vraceno_komitentu`, `izdato`, `prodato`, `reklamirano`) VALUES ('14', 'Olujni bedem', '420', '2', '0', '0', '0', '0', '0', '0', '0');
